version: '2.1'
services:
  postgresql:
    image: circleci/postgres:latest
    container_name: postgresql
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  host_catalog:
    image: host_catalog:latest
    container_name: host_catalog
    ports:
    - "8000:8000"
    environment:
      APP_DB_HOST: postgresql
    links:
      - "postgresql:postgresql"